# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Next.js deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CICD_SERVER: ${{ secrets.CICD_SERVER }}
  INFRA_KEY: ${{ secrets.INFRA_KEY }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    name: Deploy Next.js app

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm install dotenv request
    - name: Trigger CI/CD
      run: node infra/cicd/ping.js
